mqtt:
  prefix: 'system/'
  cmd_pub: 'mosquitto_pub' # 'mosquitto.pub'

apt:
  topic: 'updates/apt'
  retain: True
  run_update: False
  force_no_update: True

memory:
  topic: 'stats/memory'
  unit: 'M'
  combine: False
  pub_used_ratio: True
  pub_used_percentage: True

diskusage:
  topic: 'stats/filesystem'
  ignore: ['tmpfs','efivarfs', '/boot/efi'] # default: None
  combine: True
  output_pure: False
  output_bytes: True

uptime:
  uptime:
    topic: 'stats/uptime'
  usage:
    topic: 'stats/usage'

sensors:
  topic: 'sensors/temperatures'
  combine: True